### ISSUE TITLE
java.lang.IllegalStateException: nyi 6

### ISSUE THREAD

**Issue by knight1128** [spring-projects/spring-loaded#119]
Hi

I'm using java8 (8u40) and Intellij 14 with Java8 Lamda support on my mac.

My environment:
```
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

I have cloned https://github.com/joakim666/spring-boot-spring-loaded-java8-example and 
changed to 1.2.4.BUILD-SNAPSHOT. 

I added a test code in GreetingController.
```    
@RequestMapping("/test")
    @ResponseBody
    public String test() {
        return "greeting";
    }
```

And, I run 'mvn spring-boot:run' and changed GreetingController like below. I get :
```    
@RequestMapping("/test")
    @ResponseBody
    public String test() {
        return "greeting1";
    }
```

I have met exception nyi 6.   (I know nyi means "Not Yet Implement". ) Does it depend 'https://github.com/spring-projects/spring-loaded/commit/8381a562da8eab5e38d46164fa4679aac34fcc50' ??
```
2015-05-11 15:37:08.207 ERROR 73583 --- [Loader@14dad5dc] org.springsource.loaded.agent.Watcher    : FileWatcher caught serious error, see cause

java.lang.IllegalStateException: nyi 6
	at org.springsource.loaded.TypeDiffComputer.sameInstruction(TypeDiffComputer.java:349)
	at org.springsource.loaded.TypeDiffComputer.computeAnyMethodDifferences(TypeDiffComputer.java:205)
	at org.springsource.loaded.TypeDiffComputer.computeMethodDelta(TypeDiffComputer.java:96)
	at org.springsource.loaded.TypeDiffComputer.computeDelta(TypeDiffComputer.java:71)
	at org.springsource.loaded.TypeDiffComputer.computeDifferences(TypeDiffComputer.java:62)
	at org.springsource.loaded.ReloadableType.loadNewVersion(ReloadableType.java:322)
	at org.springsource.loaded.TypeRegistry.loadNewVersion(TypeRegistry.java:920)
	at org.springsource.loaded.agent.ReloadableFileChangeListener.fileChanged(ReloadableFileChangeListener.java:104)
	at org.springsource.loaded.agent.Watcher.determineChangesSince(FileSystemWatcher.java:251)
	at org.springsource.loaded.agent.Watcher.run(FileSystemWatcher.java:235)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by aclement** [comment]
I added support for case 6 (invoke dynamic insn node) which is what you would find in the byte code if lambdas are in the source.
