### ISSUE TITLE
NPE Exception with 1.2.3 when class is a Proxy

### ISSUE THREAD

**Issue by aantono** [spring-projects/spring-loaded#120]
Getting the following NullPointerException:
```
java.lang.NullPointerException
	at java.lang.reflect.Proxy.isProxyClass(Proxy.java:789)
	at java.lang.Class.checkPackageAccess(Class.java:2358)
	at java.lang.Class.checkMemberAccess(Class.java:2338)
	at java.lang.Class.getDeclaredField(Class.java:2054)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.injectReflectiveInterceptorMethods(SpringLoadedPreProcessor.java:420)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.tryToEnsureSystemClassesInitialized(SpringLoadedPreProcessor.java:363)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:128)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:102)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.reflect.Proxy.<clinit>(Proxy.java:240)
	at sun.reflect.misc.ReflectUtil.isNonPublicProxyClass(ReflectUtil.java:289)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:490)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.orbitz.wl.web.Application.main(Application.java:46)
java.lang.NullPointerException
	at java.lang.reflect.Proxy.isProxyClass(Proxy.java:789)
	at java.lang.Class.checkPackageAccess(Class.java:2358)
	at java.lang.Class.checkMemberAccess(Class.java:2338)
	at java.lang.Class.getDeclaredField(Class.java:2054)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.injectReflectiveInterceptorMethods(SpringLoadedPreProcessor.java:420)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.tryToEnsureSystemClassesInitialized(SpringLoadedPreProcessor.java:363)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:128)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:102)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.reflect.Proxy$ProxyClassFactory.<clinit>(Proxy.java:563)
	at java.lang.reflect.Proxy.<clinit>(Proxy.java:240)
	at sun.reflect.misc.ReflectUtil.isNonPublicProxyClass(ReflectUtil.java:289)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:490)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.orbitz.wl.web.Application.main(Application.java:46)
```

**Comment by aantono** [comment]
When trying the 1.2.4 snapshot as of 5/19, getting the same exception with a slightly different stack trace:
```
java.lang.NullPointerException
	at java.lang.reflect.Proxy.isProxyClass(Proxy.java:789)
	at java.lang.Class.checkPackageAccess(Class.java:2358)
	at java.lang.Class.checkMemberAccess(Class.java:2338)
	at java.lang.Class.getDeclaredField(Class.java:2054)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.injectReflectiveInterceptorMethods(SpringLoadedPreProcessor.java:446)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.tryToEnsureSystemClassesInitialized(SpringLoadedPreProcessor.java:386)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:132)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.reflect.Proxy.<clinit>(Proxy.java:240)
	at sun.reflect.misc.ReflectUtil.isNonPublicProxyClass(ReflectUtil.java:289)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:490)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.orbitz.wl.web.Application.main(Application.java:46)
java.lang.NullPointerException
	at java.lang.reflect.Proxy.isProxyClass(Proxy.java:789)
	at java.lang.Class.checkPackageAccess(Class.java:2358)
	at java.lang.Class.checkMemberAccess(Class.java:2338)
	at java.lang.Class.getDeclaredField(Class.java:2054)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.injectReflectiveInterceptorMethods(SpringLoadedPreProcessor.java:446)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.tryToEnsureSystemClassesInitialized(SpringLoadedPreProcessor.java:386)
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:132)
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.reflect.Proxy$ProxyClassFactory.<clinit>(Proxy.java:563)
	at java.lang.reflect.Proxy.<clinit>(Proxy.java:240)
	at sun.reflect.misc.ReflectUtil.isNonPublicProxyClass(ReflectUtil.java:289)
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:490)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.ULoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.orbitz.wl.web.Application.main(Application.java:46)
```

**Comment by aclement** [comment]
I presume these are just being logged but the system is continuing. Basically we retry that code `tryToEnsureSystemClassesInitialized` until we manage it (we want to do it as early as possible). In this case it is being attempted too early (we can see the call to 'isProxyClass' occurring in the stack below the `<clinit>` for Proxy - and `isProxyClass` checks a field which may not have been setup yet). It could be smarter about the ordering and recognize this situation but I think it is OK to just swallow this exception for now. Actually maybe I'll change it to being logged so you don't get the rogue output unless logging is on.

**Comment by aclement** [comment]
done.
