### ISSUE TITLE
ConcurrentModificationException in Grails 3.0.4 project when creating Jedis client

### ISSUE THREAD

**Issue by make** [spring-projects/spring-loaded#136]
I have Grails 3.0.4 project where I am trying to use Jedis clients asynchronously.
ConcurrentModificationException occurs when calling ```flushAll()```
```groovy
	private static def redises = [
		[host:'localhost', port:6379],
		[host:'localhost', port:16379]
	]

	static def flushAll() {
		log.info "Flushing all redises"
		withAllRedises { Jedis jedis ->
			jedis.flushAll()
		}.get()
		log.info "Flushed"
	}

	static PromiseList withAllRedises(Closure cl) {
		def tasks = new PromiseList()
		for(r in redises) {
			// Weirdness of parallellity
			def redis = r
			tasks << {
				withRedis(redis.host, redis.port, cl)
			}
		}
		tasks
	}

	static def withRedis(host, port, Closure cl) {
		Jedis jedis = null
		try {
			jedis = connectJedis(host, port)
			if(jedis)
				cl(jedis)
		} catch(e) {
			log.error("Cannot run task", e)
		} finally {
			jedis?.close()
		}
	}

	synchronized private static Jedis connectJedis(host, port) {
		JedisConnector.connectJedis(host, port)
	}

```

```java
package test;

import java.util.Date;

import redis.clients.jedis.Jedis;
import redis.clients.jedis.exceptions.JedisConnectionException;

public class JedisConnector {
	
	synchronized public static Jedis connectJedis(String host, int port) {
		Jedis jedis = new Jedis(host, port, 60000);
		try {
			jedis.set("test", new Date().toString());
		} catch(JedisConnectionException jce) {
			jedis = null;
		}
		return jedis;
	}
	
}
```

Stacktrace
```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_60]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[na:1.8.0_60]
	at org.springsource.loaded.TypeRegistry.couldBeReloadable(TypeRegistry.java:697) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.TypeRegistry.isReloadableTypeName(TypeRegistry.java:937) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.TypeRegistry.isReloadableTypeName(TypeRegistry.java:779) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.MethodInvokerRewriter$RewriteClassAdaptor$RewritingMethodAdapter.visitMethodInsn(MethodInvokerRewriter.java:1125) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sl.org.objectweb.asm.ClassReader.a(Unknown Source) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sl.org.objectweb.asm.ClassReader.b(Unknown Source) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sl.org.objectweb.asm.ClassReader.accept(Unknown Source) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sl.org.objectweb.asm.ClassReader.accept(Unknown Source) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.MethodInvokerRewriter.rewrite(MethodInvokerRewriter.java:347) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.MethodInvokerRewriter.rewrite(MethodInvokerRewriter.java:99) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.TypeRegistry.methodCallRewriteUseCacheIfAvailable(TypeRegistry.java:997) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:357) ~[springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107) [springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [na:1.8.0_60]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) [na:1.8.0_60]
	at java.lang.ClassLoader.defineClass1(Native Method) [na:1.8.0_60]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [na:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [na:1.8.0_60]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) [na:1.8.0_60]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) [na:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) [na:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) [na:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_60]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) [na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) [na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [na:1.8.0_60]
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:48) [jedis-2.7.2.jar:na]
	at redis.clients.jedis.Jedis.<init>(Jedis.java:31) [jedis-2.7.2.jar:na]
	at test.JedisConnector.connectJedis(JedisConnector.java:11) [main/:na]
	at test.JedisConnector$connectJedis.call(Unknown Source) [main/:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.4.jar:2.4.4]
	at test.Test.connectJedis(Test.groovy:197) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) [springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214) [groovy-2.4.4.jar:2.4.4]
	at test.Test.withRedis(Test.groovy:186) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) [springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.4.jar:2.4.4]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384) [groovy-2.4.4.jar:2.4.4]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182) [groovy-2.4.4.jar:2.4.4]
	at test.Test$_withAllRedises_closure6.doCall(Test.groovy:177) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) [springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.4.jar:2.4.4]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) [groovy-2.4.4.jar:2.4.4]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.4.jar:2.4.4]
	at org.grails.plugins.web.async.WebRequestPromiseDecorator.invokeClosure(WebRequestPromiseDecorator.groovy:43) [grails-plugin-async-3.0.4.jar:3.0.4]
	at org.grails.plugins.web.async.WebRequestPromiseDecorator$_decorate_closure1.doCall(WebRequestPromiseDecorator.groovy:30) [grails-plugin-async-3.0.4.jar:3.0.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) [springloaded-1.2.4.RELEASE.jar:1.2.4.RELEASE]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) [groovy-2.4.4.jar:2.4.4]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) [groovy-2.4.4.jar:2.4.4]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.4.jar:2.4.4]
	at groovy.lang.Closure.call(Closure.java:426) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:53) [groovy-2.4.4.jar:2.4.4]
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:105) [groovy-2.4.4.jar:2.4.4]
	at com.sun.proxy.$Proxy79.get(Unknown Source) [na:na]
	at reactor.rx.stream.SupplierStream$2.run(SupplierStream.java:82) [reactor-stream-2.0.3.RELEASE.jar:na]
	at reactor.core.dispatch.AbstractLifecycleDispatcher$2.accept(AbstractLifecycleDispatcher.java:136) [reactor-core-2.0.3.RELEASE.jar:na]
	at reactor.core.dispatch.AbstractLifecycleDispatcher.route(AbstractLifecycleDispatcher.java:159) [reactor-core-2.0.3.RELEASE.jar:na]
	at reactor.core.dispatch.SingleThreadDispatcher$SingleThreadTask.run(SingleThreadDispatcher.java:79) [reactor-core-2.0.3.RELEASE.jar:na]
	at reactor.core.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:156) [reactor-core-2.0.3.RELEASE.jar:na]
	at reactor.core.dispatch.RingBufferDispatcher$3.onEvent(RingBufferDispatcher.java:153) [reactor-core-2.0.3.RELEASE.jar:na]
	at reactor.jarjar.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128) [reactor-core-2.0.3.RELEASE.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by graemerocher** [comment]
@aclement This is the ConcurrentModificationException I was mentioning, would be great if this could be fixed.

**Comment by aclement** [comment]
Fix should be in a dev build a little later today.

**Comment by graemerocher** [comment]
Thanks Andy!
