### ISSUE TITLE
Issue using spring-loaded in Intellij IDEA

### ISSUE THREAD

**Issue by TonyLuo** [spring-projects/spring-loaded#149]
I use the spring-loaded in IDEA, it is working at the very beginning, I don't know why it  is suddenly not working.
VM options:  -javaagent:E:\dev\java\springloaded-1.2.4.RELEASE.jar -noverify 

"D:\Program Files\Java\jdk1.7.0_80\bin\java" -Dfile.encoding=UTF-8 -javaagent:E:\dev\java\springloaded-1.2.4.RELEASE.jar -noverify -Didea.launcher.port=7533 "-Didea.launcher.bin.path=D:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.5\bin" -classpath "D:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.5\lib\idea_rt.jar;D:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.5\lib\util.jar" com.intellij.rt.execution.CommandLineWrapper C:\Users\Administrator.USER-20150914AW\AppData\Local\Temp\classpath0.tmp com.intellij.rt.execution.application.AppMain com.yk.Application --spring.output.ansi.enabled=always
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.NoClassDefFoundError: org/springsource/loaded/TypeRegistry
	at com.yk.Application.<clinit>(Application.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:122)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.springsource.loaded.TypeRegistry
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more

**Comment by mpfaff** [comment]
Still getting this issue more than 5 years later. Yikes.
