### ISSUE TITLE
java.lang.IllegalStateException: nyi 8

### ISSUE THREAD

**Issue by lhartikk** [spring-projects/spring-loaded#153]
Loading the following code:

```
List<Integer> integers = Arrays.asList(1, 2, 3);
List<Integer> collected = integers.stream().collect(Collectors.toCollection(ArrayList::new));
```

 throws

```
	... 153 common frames omitted
[ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.lang.IllegalStateException: nyi 8] with root cause
java.lang.IllegalStateException: nyi 8
	at org.springsource.loaded.support.Java8.callLambdaMetaFactory(Java8.java:201) ~[springloaded-1.2.5.BUILD-SNAPSHOT.jar:1.2.5.BUILD-SNAPSHOT]
	at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:88) ~[springloaded-1.2.5.BUILD-SNAPSHOT.jar:1.2.5.BUILD-SNAPSHOT]
	at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1786) ~[springloaded-1.2.5.BUILD-SNAPSHOT.jar:1.2.5.BUILD-SNAPSHOT]
	at tsers.org.service.TsersService$$EPRT9Om8.getTsers(TsersService.java:16) ~[na:na]
	at tsers.org.service.TsersService$$DPRT9Om8.getTsers(Unknown Source) ~[na:na]
	at tsers.org.service.TsersService.getTsers(TsersService.java) ~[classes/:na]
	at tsers.org.service.TsersService$$FastClassByCGLIB$$27143338.invoke(<generated>) ~[spring-core-4.1.7.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at tsers.org.aop.logging.LoggingAspect.logAround(LoggingAspect.java:51) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:50) ~[springloaded-1.2.5.BUILD-SNAPSHOT.jar:1.2.5.BUILD-SNAPSHOT]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1461) ~[springloaded-1.2.5.BUILD-SNAPSHOT.jar:1.2.5.BUILD-SNAPSHOT]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:58) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.7.RELEASE.jar:4.1.7.RELEASE]
```

**Comment by lhartikk** [comment]
Created a proposal for fix
#154

**Comment by aclement** [comment]
committed your change, thanks for that (and taking time to create a test case)
