### ISSUE TITLE
 Reloading agent exited via exception

### ISSUE THREAD

**Issue by xsjk** [spring-projects/spring-loaded#159]
```
java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira
        at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:110)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:77)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:140)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1057)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1038)
        at java.lang.reflect.Field.getLong(Field.java:591)
        at java.io.ObjectStreamClass.__sljlrfgl(ObjectStreamClass.java)
        at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1663)
                                                                                                                                                              203,1         68%
        at org.apache.mina.common.support.AbstractIoFilterChain$HeadFilter.sessionOpened(AbstractIoFilterChain.java:480)
        at org.apache.mina.common.support.AbstractIoFilterChain.callNextSessionOpened(AbstractIoFilterChain.java:248)
        at org.apache.mina.common.support.AbstractIoFilterChain.fireSessionOpened(AbstractIoFilterChain.java:243)
        at org.apache.mina.common.support.IoServiceListenerSupport.fireSessionCreated(IoServiceListenerSupport.java:180)
        at org.apache.mina.transport.socket.nio.SocketIoProcessor.doAddNew(SocketIoProcessor.java:152)
        at org.apache.mina.transport.socket.nio.SocketIoProcessor.access$200(SocketIoProcessor.java:45)
        at org.apache.mina.transport.socket.nio.SocketIoProcessor$Worker.run(SocketIoProcessor.java:484)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
        at java.util.HashMap$EntryIterator.next(HashMap.java:966)
        at java.util.HashMap$EntryIterator.next(HashMap.java:964)
        at org.springsource.loaded.agent.SpringLoadedPreProcessor.tryToEnsureSystemClassesInitialized(SpringLoadedPreProcessor.java:373)
        at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:135)
        at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
        ... 56 more
```

**Comment by yarhoo** [comment]
try #218
