### ISSUE TITLE
[1.2.6] NPE in Java8.java when dealing with lambda

### ISSUE THREAD

**Issue by darylteo** [spring-projects/spring-loaded#173]
``` bash
java.lang.NullPointerException: null
at org.springsource.loaded.support.Java8.callLambdaMetaFactory(Java8.java:153)
at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:88)
... 81 common frames omitted
Causing: java.lang.RuntimeException: java.lang.NullPointerException
at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:92)
at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1791)
at com.listcorp.services.api.model.Urls$$EPmmp1yi.url(Urls.java:21)
at com.listcorp.services.api.model.Urls$$DPmmp1yi.url(Unknown Source)
at com.listcorp.services.api.model.Urls.url(Urls.java)
... trimmed
```

Urls.java

``` java
package com.redacted.services.api.model;

import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

public class Urls {
    public static URI url(Object... args) {
        try {
            /* flattening the paths */
            final List<String> paths = Arrays
                .stream(args)
                .flatMap(arg -> {
                    if (arg instanceof Collection) {
                        return ((Collection<Object>) arg).stream();
                    } else if (arg instanceof Object[]) {
                        return Arrays.stream((Object[]) arg);
                    }

                    return Arrays.stream(new Object[]{
                        arg
                    });
                })
                .map(Object::toString)
                .map(String::toLowerCase)
                .collect(Collectors.toList());

            Path path = Paths.get("/", paths.toArray(new String[0]));
            URI uri = new URI("https", "www.redacted.com", path.toString(), null);

            return uri;
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }
}
```

Other notes that I hope will help:
- Line 21 refers to flatMap.
- this is in a Gradle build, but with --no-daemon, and -t flag (continuous integration)
- framework is dropwizard

Kind Regards,
Daryl

**Comment by darylteo** [comment]
Just looking at the source, there does seem like there is a logical error here?

Java8.java:153

```java
				if (null == ownerRType || !ownerRType.hasBeenReloaded()) {
					// target containing the reference/lambdaMethod has not been reloaded, no need to get over
					// complicated.
					Class<?> ownerClazz = ownerRType.getClazz();
					implMethod = caller.findVirtual(ownerClazz, name, implMethodType);
				}
````

If ownerRType is null, the NPE occurs when calling ownerRType.getClazz();

Not that I would know why ownerRType would be null. Haven't gotten that far yet.
