### ISSUE TITLE
NPE in Java8.callLambdaMetaFactory with 1.2.5

### ISSUE THREAD

**Issue by axelfontaine** [spring-projects/spring-loaded#175]
```
java.lang.NullPointerException: null
    at org.springsource.loaded.support.Java8.callLambdaMetaFactory(Java8.java:153)
    at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:88)
```

**Comment by fornwall** [comment]
From [Java8.java](https://github.com/spring-projects/spring-loaded/blob/91e3e652aa56392c6dae4af88eb5f6b11153ac64/springloaded/src/main/java/org/springsource/loaded/support/Java8.java#L150):

```java
if (null == ownerRType || !ownerRType.hasBeenReloaded()) {
    // target containing the reference/lambdaMethod has not been reloaded, no need to get over
    // complicated.
    Class<?> ownerClazz = ownerRType.getClazz();
    implMethod = caller.findVirtual(ownerClazz, name, implMethodType);
}
```

If `ownerRType` is null it immediately is dereferenced leading to this NPE.

**Comment by fornwall** [comment]
Duplicated of https://github.com/spring-projects/spring-loaded/issues/173.
