### ISSUE TITLE
spring-loaded java 10/9 supports

### ISSUE THREAD

**Issue by xingxiuyi** [spring-projects/spring-loaded#210]
spring-loaded report error when running in jdk 10/9

This project has any plan to support new java version 10 and 9 ? 

```
org.springsource.loaded.agent.SpringLoadedPreProcessor preProcess
error: Unexpected problem transforming call sites
java.lang.IllegalArgumentException
at sl.org.objectweb.asm.ClassReader.<init>(Unknown Source)
at sl.org.objectweb.asm.ClassReader.<init>(Unknown Source)
at org.springsource.loaded.MethodInvokerRewriter.rewrite(MethodInvokerRewriter.java:345)
at org.springsource.loaded.MethodInvokerRewriter.rewrite(MethodInvokerRewriter.java:99)
at org.springsource.loaded.TypeRegistry.methodCallRewriteUseCacheIfAvailable(TypeRegistry.java:1002)
at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:361)
at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:560)
at java.base/java.lang.ClassLoader.defineClass2(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1101)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:760)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:681)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:606)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)

```

**Comment by niqingyang** [comment]
I have the same problem.Now I have to use java8...

**Comment by fcappi** [comment]
Any update on this?

**Comment by rodolfosaraiva** [comment]
+1, I still need support for java 11+, any solution?
