### ISSUE TITLE
Tomcat 7.0.25 startup error

### ISSUE THREAD

**Issue by emrahkocaman** [spring-projects/spring-loaded#46]
I've a webapp (Spring-3.1.0 + Struts 1.3.10 + JSF 2.1) which runs on Tomcat 7.0.25 with sun jdk 1.6.0_30. 
After adding springloaded-1.1.5 javaagent to the tomcat vm parameters, the below exception is thrown and tomcat does not start.

> INFO: Initializing Spring root WebApplicationContext
> java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira
>     at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:104)
>     at sun.instrument.TransformerManager.transform(TransformerManager.java:169)
>     at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:365)
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
>     at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2836)
>     at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1160)
>     at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1668)
>     at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1546)
>     at org.springframework.util.ClassUtils.forName(ClassUtils.java:257)
>     at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:417)
>     at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1283)
>     at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1254)
>     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:576)
>     at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1331)
>     at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:317)
>     at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:396)
>     at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:612)
>     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:446)
>     at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:384)
>     at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
>     at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
>     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4779)
>     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5273)
>     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1568)
>     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1558)
>     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
>     at java.lang.Thread.run(Thread.java:662)
> Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.teb.pusula.frmw.common.utils.StringUtil__I
>     at sl.org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
>     at sl.org.objectweb.asm.ClassWriter.a(Unknown Source)
>     at sl.org.objectweb.asm.Frame.a(Unknown Source)
>     at sl.org.objectweb.asm.Frame.a(Unknown Source)
>     at sl.org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
>     at sl.org.objectweb.asm.ClassReader.accept(Unknown Source)
>     at sl.org.objectweb.asm.ClassReader.accept(Unknown Source)
>     at sl.org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
>     at org.springsource.loaded.ReloadableType$MergedRewrite$ChainedAdapters.getBytes(ReloadableType.java:856)
>     at org.springsource.loaded.ReloadableType$MergedRewrite.rewrite(ReloadableType.java:836)
>     at org.springsource.loaded.ReloadableType.rewriteCallSitesAndDefine(ReloadableType.java:809)
>     at org.springsource.loaded.ReloadableType.<init>(ReloadableType.java:155)
>     at org.springsource.loaded.TypeRegistry.addType(TypeRegistry.java:909)
>     at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:283)
>     at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:102)
>     ... 33 more

**Comment by swaprks** [comment]
This is a problem with springloaded-1.2.1. Please use a new version of springloaded-1.2.2 or springloaded-1.2.3
