### ISSUE TITLE
Bug when using java8 method reference

### ISSUE THREAD

**Issue by amidudu** [spring-projects/spring-loaded#87]
Hi,

When reloaded class with the below code:

List<String> list = new ArrayList<>();
list.add("test3");
list.stream().collect(Collectors.toMap(String::length, Function.<String>identity()));

An exception is thrown:

javax.servlet.ServletException: java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: com.example.rest.ExampleAPI$$EOqhSaWw.length(String)int/invokeStatic
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:391)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at com.example.utils.ReloadableJerseyServletContainer.service(ReloadableJerseyServletContainer.java)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:534)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
	at com.example.utils.ReloadableJerseyServletContainer.doFilter(ReloadableJerseyServletContainer.java)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
	at com.example.utils.ReloadableJerseyServletContainer.doFilter(ReloadableJerseyServletContainer.java)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.example.utils.RequestFilter.doFilter(RequestFilter.java:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:655)
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:277)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2381)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2370)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: com.example.rest.ExampleAPI$$EOqhSaWw.length(String)int/invokeStatic
	at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:97)
	at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1574)
	at com.example.rest.ExampleAPI$$EOqhSaWw.getCandidateSkills(ExampleAPI.java:843)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springsource.loaded.ri.ReloadedTypeInvoker$2.invoke(ReloadedTypeInvoker.java:122)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	... 29 more
Caused by: java.lang.NoSuchMethodException: no such method: com.example.rest.ExampleAPI$$EOqhSaWw.length(String)int/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:876)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:993)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1379)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:776)
	at org.springsource.loaded.support.Java8.callLambdaMetaFactory(Java8.java:146)
	at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:94)
	... 55 more
Caused by: java.lang.NoSuchMethodError: com.example.rest.ExampleAPI$$EOqhSaWw.length(Ljava/lang/String;)I
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:965)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:990)
	... 59 more

**Comment by ilx** [comment]
+1. Same here.

**Comment by ilx** [comment]
I was thinkering with Java8#callLambdaMetaFactory:

```
            case Opcodes.H_INVOKEVIRTUAL:
                // If there is an executor, the lambda function is actually modified from 'private instance' to 'public static' so adjust lookup. The method
                // will be static with a new leading parameter.
                // TODO when can this scenario occur? Aren't we only here if reloading has happened?
                // A: when we're about to invoke reference method from a class that wasn't rewritten
                // say we have a rest service AccountResource that invokes Authority::getName()
                // if we change Authority, executorClass will be null, AccountResource is not reloaded yet,
                // and we need to invoke getName on rewritten Authority
                TypeRegistry typeRegistry = rtype.getTypeRegistry();
                int ownerTypeId = typeRegistry.getTypeIdFor(owner, false);
                ReloadableType ownerReloadableType = typeRegistry.getReloadableType(ownerTypeId);
                if (null != ownerReloadableType) {
                    MethodMember currentMethod = ownerReloadableType.getCurrentMethod(name, descriptor);
                    CurrentLiveVersion liveVersion = ownerReloadableType.getLiveVersion();
                    if (null != liveVersion ) {
                        Class<?> ownerExecutorClass = liveVersion.getExecutorClass();
                        Method executorMethod = liveVersion.getExecutorMethod(currentMethod);
                        String methodDescriptor = Type.getType(executorMethod).getDescriptor();
                        MethodType type = MethodType.fromMethodDescriptorString(methodDescriptor,callerLoader);
                        implMethod = caller.findStatic(ownerExecutorClass, name, type);

                        // if we change something in the class that caller references then caller has to update it's reference
                        // I don't know if this is the best way to do it
                        if (!rtype.hasBeenReloaded()) {
                            rtype.simulateReload();
                        }
                    }
                    else {
                        // AccountResource uses method reference to Authority::getName()
                        // and we made a change only in AccountResource
                        Class<?> refc = ownerReloadableType.getClazz();
                        implMethod = caller.findVirtual(refc, name, implMethodType);
                    }
                } else {
                    // IMPORTANT: don't know where this happens so I'm leaving it for backwards (in)compatibility
                    implMethod = caller.findVirtual(caller.lookupClass(), name, implMethodType);
                }
                break;
```

seems to work quite nicely

**Comment by ealmasnci** [comment]
Same here... it's looking for the method on the class calling .stream() instead of looking for the property on the entity that I'm traversing inside of the stream.

**Comment by crystoll** [comment]
Yup, suffering same issue with Springloaded version 1.2.3

**Comment by shredmaster** [comment]
i am having the same issue. when will this fix be included in next release?

**Comment by aclement** [comment]
This will be in a release very soon - I've taken the proposed pull request, reworked it a bit and covered it all with test cases (some from the PR, some new ones).

**Comment by aclement** [comment]
Fixes and tests all in. Vaguely suspect the other kinds of handling (static/interface/special) will need some love too (in addition to the virtual case fixed up here).

**Comment by eau-de-la-seine** [comment]
Hi, same problem here with spring-boot 1.4.1 and spring-loaded 1.2.6 when I use a **method reference**:
`java.lang.RuntimeException: java.lang.NullPointerException
	at org.springsource.loaded.support.Java8.emulateInvokeDynamic(Java8.java:92)
	at org.springsource.loaded.TypeRegistry.idyrun(TypeRegistry.java:1791)
	at com.project.filters.AuthenticationFilter.doFilter(AuthenticationFilter.java:53)`
