### ISSUE TITLE
Agent exits due to ConcurrentModficiationException

### ISSUE THREAD

**Issue by graemerocher** [spring-projects/spring-loaded#9]
Occasionally I see the dreaded Spring loaded agent exiting error which is caused by:

| Error Caused by: java.util.ConcurrentModificationException
| Error     at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372)
| Error     at java.util.AbstractList$Itr.next(AbstractList.java:343)
| Error     at org.springsource.loaded.TypeRegistry.isReloadableTypeName(TypeRegistry.java:695)
| Error     at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:160)
| Error     at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:102)
| Error     ... 187 more

**Comment by davydotcom** [comment]
I can make it happen every time in grails 3.0.2 with handlebars-asset-pipeline installed and a few hbs files. very odd

**Comment by aclement** [comment]
If you can attach a failing sample (or email me one) I can dig into it. I suspect it is related to the package name cache we keep which records which packages we are currently considering reloadable.
