### ISSUE TITLE
Spring loaded + jboss - NoClassDefFoundError

### ISSUE THREAD

**Issue by pootek** [spring-projects/spring-loaded#94]
I've added

```
-javaagent:C:/springloaded-1.2.1.RELEASE.jar -noverify
```

to JAVA_OPTS in bin/standalone.conf.bat.

During startup java correctly finds and loads spring-loaded as java agent, but when tries to load a class it gives me this and dies:

```
WARNING: Failed to load the specified log manager class org.jboss.logmanager.LogManager
java.lang.NoClassDefFoundError: org/springsource/loaded/ri/ReflectiveInterceptor
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2253)
        at org.jboss.logging.Logger.getMessageLogger(Logger.java:2211)
        at org.jboss.msc.service.ServiceLogger.<clinit>(ServiceLogger.java:42)
        at org.jboss.msc.service.ServiceContainerImpl.<clinit>(ServiceContainerImpl.java:91)
        at org.jboss.msc.service.ServiceContainer$Factory.create(ServiceContainer.java:147)
        at org.jboss.as.server.BootstrapImpl.<init>(BootstrapImpl.java:51)
        at org.jboss.as.server.Bootstrap$Factory.newInstance(Bootstrap.java:212)
        at org.jboss.as.server.Main.main(Main.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at org.jboss.modules.Module.run(Module.java:270)
        at org.jboss.modules.Main.main(Main.java:411)
Caused by: java.lang.ClassNotFoundException: org.springsource.loaded.ri.ReflectiveInterceptor from [Module "org.jboss.logging:main" from local module loader @5fd4a617 (finder: local module finder @1e46128 (roots: C:\jboss\modules,C:\jboss\modules\system\layers\base))]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:196)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:444)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:432)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:374)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:119)
        ... 15 more
```

Could you please help me out.

**Comment by ser10us** [comment]
I have had the same issue. It seems to arise when Spring Loaded agent tries to log something at the time when the log library is not yet available.
I was able to fix this by adding the following options:
* -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager,org.springsource"
* -Djava.util.logging.manager=org.jboss.logmanager.LogManager
* -Xbootclasspath/p:*/your/path*/jboss-eap-6.2.4/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-1.5.1.Final-redhat-1.jar"
* -Xbootclasspath/p:*/your/path*/jboss-eap-6.2.4/modules/system/layers/base/org/jboss/log4j/logmanager/main/log4j-jboss-logmanager-1.0.1.Final.jar"

**Comment by prasadbhima** [comment]
thanks. I got into same issue and resolved with above steps

**Comment by oshadami** [comment]
I resolved same issue with the above steps, thanks @ser10us
